# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules =
        [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
      kernelModules = [ ];
      luks.devices."cryptroot".device =
        "/dev/disk/by-uuid/5b3b1e72-3dce-44a3-a24f-2271797e6c3a";
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=2G" "mode=755" "noexec" ];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/10DE-CC97";
      fsType = "vfat";
    };
    "/nix" = {
      device = "/dev/disk/by-uuid/70ef31c0-02ad-4dd3-9a79-e83788a42f15";
      fsType = "xfs";
    };

    "/etc/nixos".options = [ "noexec" ];
    "/srv".options = [ "noexec" ];
    "/var/lib".options = [ "noexec" ];
    "/var/log".options = [ "noexec" ];
    "/etc/innernet".options = [ "noexec" ];
    "/usr/share/secureboot".options = [ "noexec" ];
    "/etc/secureboot".options = [ "noexec" ];
    "/home/tht".options = [ "noexec" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
